my_blog/urls.py
from my_blog import views

from django.urls import path
from django.views.decorators.cache import cache_page

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    # path('author-list/<str:slug>/', views.AuthorInfo.as_view(), name='author-detail'),
    # path('author-list/', views.AuthorsList.as_view(), name='author-list'),
    # path('book-list/<str:slug>/', views.BookInfo.as_view(), name='book-detail'),
    # path('book-list/', cache_page(10 * 60)(views.BooksList.as_view()), name='book-list'),
    # path('book-create/', views.BookFormCreateView.as_view(), name='book-create'),
    # path('book-view/<str:slug>/', views.BookFormView.as_view(), name='book-view'),
    # path('book-update/<str:slug>/', views.BookFormUpdateView.as_view(), name='book-update'),
    # path('book-delete/<str:slug>/', views.BookFormDeleteView.as_view(), name='book-delete'),
    # path('publisher-list/<str:slug>/', views.PublisherInfo.as_view(), name='publisher-detail'),
    # path('publisher-list/', views.PublishersList.as_view(), name='publisher-list'),
    # path('store-list/<str:slug>/', views.StoreInfo.as_view(), name='store-detail'),
    # path('store-list/', views.StoresList.as_view(), name='store-list'),
]

practic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views


urlpatterns = [
    path('', include('my_blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path("accounts/login/", auth.views.LoginView.as_view(template_name='admin/login.html'), name="login"),
    path('__debug__/', include('debug_toolbar.urls')),
]

my_blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('my_blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

my_blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

my_blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'my_blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'my_blog/post_detail.html', {'post': post})


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'my_blog/post_edit.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'my_blog/post_edit.html', {'form': form})


@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'my_blog/post_draft_list.html', {'posts': posts})


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

templates/my_blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Django Girls blog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/my_blog.css' %}">
    </head>
    <body>
    <header class="page-header">
        <div class="container">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-file"></span></a>
                <p class="top-menu">Hello, {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="/">Django Girls Blog</a></h1>
        </div>
    </header>
    <main class="container">
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
    </body>
</html>

templates/my_blog/post_detail.html
{% extends 'my_blog/base.html' %}

{% block content %}
    <article class="post">
        <aside class="actions">
            {% if post.published_date %}
                <time class="date">
                    {{ post.published_date }}
                </time>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'blog:post_edit' pk=post.pk %}">
                  {% include './icons/pencil-fill.svg' %}
                </a>
            {% endif %}
            <a class="btn btn-secondary" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        </aside>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </article>
{% endblock %}

templates/my_blog/post_draft_list.html
{% extends 'my_blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <article class="post">
            <time class="date">
                created: {{ post.created_date|date:'d-m-Y' }}
            </time>
            <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr|truncatechars:300 }}</p>
        </article>
    {% endfor %}
{% endblock %}

templates/my_blog/post_edit.html
{% extends 'my_blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

templates/my_blog/post_list.html
{% extends 'my_blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <article class="post">
            <time class="date">
                {{ post.published_date }}
            </time>
            <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr|truncatechars:300 }}</p>
        </article>
    {% endfor %}
{% endblock %}